<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class pegawai extends CI_Controller {

    function __construct() {
        parent::__construct();
        $this->load->model('pegawai_model');
        $this->load->library('form_validation');
        chek_session();
    }

    public function index() {
        $pegawai = $this->pegawai_model->get_all();

        $data = array(
            'pegawai_data' => $pegawai
        );

        $this->template->display('pegawai/tb_pegawai_list', $data);
    }



    public function read($id) {
        $row = $this->pegawai_model->get_by_id($id);
        if ($row) {
            $data = array(
                'id_pegawai' => $row->id_pegawai,
                'nama_pegawai' => $row->nama_pegawai,
                'jabatan' => $row->jabatan,
            );
            $this->template->display('pegawai/tb_pegawai_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('pegawai'));
        }
    }

  
    

    public function update($id) {
        $row = $this->pegawai_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('pegawai/update_action'),
                'id_pegawai' => set_value('id_pegawai', $row->id_pegawai),
                'nama_pegawai' => set_value('nama_pegawai', $row->nama_pegawai),
                'jabatan' => set_value('jabatan', $row->jabatan),
            );
            $this->template->display('pegawai/tb_pegawai_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('pegawai'));
        }
    }

    public function update_action() {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id_pegawai', TRUE));
        } else {
            $data = array(
                'nama_pegawai' => $this->input->post('nama_pegawai', TRUE),
                'jabatan' => $this->input->post('jabatan', TRUE),
                
            );

            $this->pegawai_model->update($this->input->post('id_pegawai', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('pegawai'));
        }
    }

    public function delete($id) {
        $row = $this->pegawai_model->get_by_id($id);

        if ($row) {
            $this->pegawai_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('pegawai'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('pegawai'));
        }
    }

    public function _rules() {
        $this->form_validation->set_rules('nama_pegawai', 'nama_pegawai', 'trim|required');
        $this->form_validation->set_rules('jabatan', 'jabatan', 'trim|required');
        $this->form_validation->set_rules('id_pegawai', 'id_pegawai', 'trim');
        $this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file pegawai.php */
/* Location: ./application/controllers/pegawai.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-05-14 11:06:57 */
/* http://harviacode.com */