<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class rjtp extends CI_Controller {

    function __construct() {
        parent::__construct();
        $this->load->model('rjtp_model');
        $this->load->library('form_validation');
        chek_session();
    }

    public function index() {
        $rjtp = $this->rjtp_model->get_all();

        $data = array(
            'rjtp_data' => $rjtp
        );

        $this->template->display('rjtp/tb_rjtp_list', $data);
    }





  
    public function create() {
        $data = array(
            'button' => 'Create',
            'action' => site_url('rjtp/create_action'),
            'kode_program' => set_value('kode_program'),
            'nama_program' => set_value('nama_program'),
            'uraian' => set_value('uraian'),
            'kode_akun' => set_value('kode_akun'),
            'pel' => set_value('pel'),
            'id_pelayanan'=> set_value('id_pelayanan'),
           
        );
        $this->template->display('rjtp/tb_rjtp_form', $data);
    }

    public function create_action() {

            $data = array(
                'kode_program' => $this->input->post('kode_program', TRUE),
                'nama_program' => $this->input->post('nama_program', TRUE),
                'uraian' => $this->input->post('uraian', TRUE),
                'kode_akun' => $this->input->post('kode_akun', TRUE),
                'pel' => $this->input->post('pel', TRUE),
                'id_pelayanan' => $this->input->post('id_pelayanan', TRUE),
                
            );

            $this->rjtp_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('rjtp'));
       
    }

    public function update($kd) {
        $row = $this->rjtp_model->get_by_kd($kd);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('rjtp/update_action'),
                'kode_program' => set_value('kode_program', $row->kode_program),
                'nama_program' => set_value('nama_program', $row->nama_program),
                'uraian' => set_value('uraian', $row->uraian),
                'kode_akun' => set_value('kode_akun', $row->kode_akun),
                'id_pelayanan' => set_value('id_pelayanan', $row->id_pelayanan),
            );
            $this->template->display('rjtp/tb_rjtp_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('rjtp'));
        }
    }

    public function update_action() {

        
            $data = array(
                'id' => $this->input->post('id', TRUE),
                'kode_program' => $this->input->post('kode_program', TRUE),
                'nama_program' => $this->input->post('nama_program', TRUE),
                'uraian' => $this->input->post('uraian', TRUE),
                'kode_akun' => $this->input->post('kode_akun', TRUE),
                'id_pelayanan' => $this->input->post('id_pelayanan', TRUE),
            );

            $this->rjtp_model->update($this->input->post('id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('rjtp'));
        
    }

    public function delete($kd) {
        $row = $this->rjtp_model->get_by_kd($kd);

        if ($row) {
            $this->rjtp_model->delete($kd);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('rjtp'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('rjtp'));
        }
    }

    public function _rules() {
        $this->form_validation->set_rules('kode_program', 'kode_program', 'trim|required');
        $this->form_validation->set_rules('nama_program', 'nama_program', 'trim|required');
        $this->form_validation->set_rules('uraian', 'uraian', 'trim|required');
        $this->form_validation->set_rules('kode_akun', 'kode_akun', 'trim|required');
        $this->form_validation->set_rules('pel', 'pel', 'trim|required');
        $this->form_validation->set_rules('id_pelayanan', 'id_pelayanan', 'trim');
        $this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

    
    

}

/* End of file rjtp.php */
/* Location: ./application/controllers/rjtp.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-05-14 11:06:57 */
/* http://harviacode.com */